services:
  - type: web
    name: elevatr-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /api/health